Add dep `@libsql/linux-x64-gnu`
```json
{"type":"error","code":"deploymentFailed","ctx":"The deployment failed: UNCAUGHT_EXCEPTION\n\nError: Cannot find module '@libsql/linux-x64-gnu'\nRequire stack:\n- /node_modules/.deno/libsql@0.5.17/node_modules/libsql/index.js\n- /node_modules/.deno/libsql@0.5.17/node_modules/libsql/index.js\n    at Module._resolveFilename (node:module:619:15)\n    at Module._load (node:module:497:27)\n    at Module.require (node:module:681:19)\n    at require (node:module:816:16)\n    at requireNative (file:///node_modules/.deno/libsql@0.5.17/node_modules/libsql/index.js:26:10)\n    at Object.<anonymous> (file:///node_modules/.deno/libsql@0.5.17/node_modules/libsql/index.js:52:5)\n    at Object.<anonymous> (file:///node_modules/.deno/libsql@0.5.17/node_modules/libsql/index.js:443:4)\n    at Module._compile (node:module:745:34)\n    at loadMaybeCjs (node:module:770:10)\n    at Object.Module._extensions..js (node:module:755:12)"}
```